### ISSUE TITLE
Proxy setting in CogniteClient

### ISSUE THREAD

**Issue by y-Blandin-Luc** [cognitedata/cdf-sdk-java#157]
Hi Cognite Developement Team

We are developping an application using `cdf-sdk-java` version 1.13.0 and when executing the following code in an environment where the proxy authentification is mandatory, the exceptions `java.net.SocketTimeoutException: connect timed out` or `java.io.ioexception failed to authenticate with proxy` occur.

```java
CogniteClient	client = CogniteClient.ofClientCredentials(clientId, clientSecret, TokenUrl.generateAzureAdURL(azureAdTenantId)).withProject(projectId);			
Iterator<List<TimeseriesMetadata>> iteratorTs = client.timeseries().list();
```
We would like to have the possiblity in the Cognite client to set the proxy information (hostname, port number, user, password) for the `OkHttpClient `.

Thank you.

**Comment by kjetilh33** [comment]
Hi,

Thank you for bringing this issue to our attention. We have added support for configuring proxy server settings to the upcoming SDK release (estimated to be v 1.17.0).

Cheers,
Cognite
