### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by alex-osadchyi** [cognitedata/cdf-sdk-java#36]
Is it planned to support Java 8?

Now when I'm trying to use SDK with java 8, I get an error:
java: cannot access com.cognite.client.CogniteClient
  bad class file: ~/.m2/repository/com/cognite/cdf-sdk-java/0.9.6/cdf-sdk-java-0.9.6.jar!/com/cognite/client/CogniteClient.class
    class file has wrong version 55.0, should be 52.0

**Comment by kjetilh33** [comment]
Hi. 

Thanks for filing the issue. We are targeting Java 11 support for the SDK. 

Java 8 is not supported per now. This should be better documented by us--we'll fix that asap. 

Do you have a hard requirement for Java 8? Asking just to evaluate the business case.

**Comment by alex-osadchyi** [comment]
Hi,
We've switched to Java 11, so this issue is not relevant for us anymore.
