### ISSUE TITLE
Logging configuration file name

### ISSUE THREAD

**Issue by alex-osadchyi** [cognitedata/cdf-sdk-java#37]
Logging configuration file is named **logback-test.xml** and is placed under src/**main**/resources (https://github.com/cognitedata/cdf-sdk-java/blob/main/src/main/resources/logback-test.xml).

Was this file name chosen on purpose?
The problem with this name is that it takes precedence over the name **logback.xml**, as it stated in the logback [docs](http://logback.qos.ch/manual/configuration.html#auto_configuration): 

> Logback tries to find a file called logback-test.xml in the classpath.
> If no such file is found, logback tries to find a file called logback.groovy in the classpath.
> If no such file is found, it checks for the file logback.xml in the classpath.

If I use cdf-sdk-java dependency for my project it overrides my logging configuration defined in **logback.xml**, because of this naming. Is it possible to rename it according to the logback naming convention? From the same [doc](http://logback.qos.ch/manual/configuration.html#auto_configuration):

> If you are using Maven and if you place the logback-test.xml under the src/test/resources folder, Maven will ensure that it won't be included in the artifact produced. Thus, you can use a different configuration file, namely logback-test.xml during testing, and another file, namely, logback.xml, in production.

**Comment by kjetilh33** [comment]
Fixed in the upcoming release 0.9.9.
