### ISSUE TITLE
Delete `.tmp` files 

### ISSUE THREAD

**Issue by Misolini** [cognitedata/cdf-sdk-java#62]
If files are downloaded after having done one or more retries, the original `.tmp` files that did not result in a successful file download are not deleted.

![Screenshot 2021-10-14 at 13 49 24](https://user-images.githubusercontent.com/17146610/137311835-5016b782-6b9e-4a74-b65b-576650066e8d.png)

**Comment by cognite-ornellas** [comment]
I am closing this issue as it is fixed in the latest version.
